apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: drug-search-tailwind
  name: drug-search-tailwind
spec:
  host: drug-search-tailwind-dpd.apps-crc.testing
  port:
    targetPort: 8080
  to:
    kind: Service
    name: drug-search-tailwind
    weight: null
status:
  ingress: null
